name: "image"
description: >-
   Build a docker image from Dockerfile.
   The image will be pushed if the action if a tag has been pushed.
   In addition to the git tag the image will tagged 'latest' if we are on the default branch.

inputs:
  registry:
    description: "Docker registry"
    required: true

  username:
    description: "Username for login to registry"
    required: true

  password:
    description: "Password for login to registry"
    required: true

  image:
    description: "Image name"
    required: true

  dockerfile:
    description: "Path to Dockerfile"
    required: false
    default: Dockerfile

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.registry }}/${{ inputs.image }}

        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: "."
        file: ${{ inputs.dockerfile }}
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:latest
        cache-to: type=inline
